# Generated by Django 5.2.13 on 2026-04-25 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(editable=False, max_length=12, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('business_type', models.CharField(choices=[('retail', 'Retail shop'), ('salon', 'Salon / Barbershop'), ('pharmacy', 'Pharmacy'), ('restaurant', 'Restaurant / Cafe'), ('other', 'Other')], max_length=30)),
                ('country', models.CharField(max_length=60)),
                ('currency', models.CharField(default='KES', max_length=10)),
                ('logo', models.ImageField(blank=True, upload_to='logos/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OnboardingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_product', models.BooleanField(default=False)),
                ('made_first_sale', models.BooleanField(default=False)),
                ('added_staff', models.BooleanField(default=False)),
                ('viewed_reports', models.BooleanField(default=False)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tenants.business')),
            ],
        ),
    ]
