# Generated by Django 5.2.13 on 2026-04-26 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='business_type',
            field=models.CharField(choices=[('retail', 'Retail shop'), ('salon', 'Salon / Barbershop'), ('pharmacy', 'Pharmacy'), ('restaurant', 'Restaurant / Café'), ('wholesale', 'Wholesale'), ('other', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='onboardingprogress',
            name='business',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding', to='tenants.business'),
        ),
    ]
