# Generated by Django 5.2.13 on 2026-04-25 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('owner', 'Owner'), ('manager', 'Manager'), ('cashier', 'Cashier')], default='cashier', max_length=20),
        ),
    ]
